version: "3"

services:
  backend:
    restart: always
    env_file:
      - .env
    image: ${PROJECT}:latest
    build:
      dockerfile: Dockerfile
      args:
        DockerHOME: ${DockerHOME}
        DockerPORT: ${DockerPORT}

    container_name: ${PROJECT}_backend
    ports:
      - ${DockerPORT}:${DockerPORT}
    volumes:
      - ~/.PYTHON/django_tests/dj_docker:${DockerHOME}

    depends_on:
      - postgresql
    links:
      - postgresql

  postgresql:
    restart: always
    env_file: .env
    image: postgres:13.1-alpine

    container_name: ${PROJECT}_postgres
    ports:
      - ${PostgresPORT}:${PostgresPORT}
    volumes:
      - ./data/pgdata:${PostgresHOME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: ${PostgresHOME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
